# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73198feae9d46aa6ae19656e87e1501d3f5f019578dd52e33014524f031a09bf8334d10d9eb6f1de947743f39b61fbe6d89681f74e0e698af4a036ab84ac9389

test:
  secret_key_base: 6821b1fc1f484a8bbad4bc957ce52329f774a2b05eaf9f8ad7addc81aa27b29fa7f21761b702e0ddddedf413a715394750f397f973f28998777943cdfde61b2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
